#!/bin/bash
set -e

curl -o /tmp/release https://raw.githubusercontent.com/caarlos0/go-releaser/master/release
chmod +x /tmp/release
/tmp/release -u ContaAzul -r hystrix-to-librato -b hystrix-to-librato -m .
